title: "Tiago Belintani"
description: "Evolutionary Bioinformatician | Postdoctoral Fellow (UNESP/FAPESP)"
url: ""          
baseurl: ""      

author:
  name: "Tiago Belintani"
  email: "tiagobellintani@gmail.com"
  motto: "Sapientia et disciplina"
  scholar: "https://scholar.google.com/citations?user=Ah8QjuIAAAAJ&hl=pt-BR"
  fapesp: "https://bv.fapesp.br/pt/pesquisador/728865/tiago-belintani/"
  researchgate: "https://www.researchgate.net/profile/Tiago-Belintani"
  orcid: "https://orcid.org/0000-0001-9485-1145"
  lattes: "http://lattes.cnpq.br/8948388411348223"
  researcherid: "https://www.webofscience.com/wos/author/record/AAL-8293-2021"

github_username: "TiagoBelintani"

markdown: kramdown
plugins:
  - jekyll-seo-tag

exclude:
  - README.md

